---

- name: Include specified dotfile tasks
  ansible.builtin.include_tasks: "{{ item }}"
  loop: "{{ dotfile_tasks }}"

- name: Ensure target_user owns their .config directory
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.config"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    recurse: true
