---

- name: Include specified dotfile tasks
  ansible.builtin.include_tasks: "{{ dotfile_task }}"
  loop: "{{ dotfile_tasks }}"
  loop_control:
    loop_var: dotfile_task

- name: Ensure target_user owns their .config directory
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.config"
    owner: "{{ target_user }}"
    recurse: true
