---

- name: Deploy alacritty
  hosts: all
  vars_files:
    - ./vars/fonts.yml
    - ./vars/colorscheme.yml
  vars:
    dotfile_tasks:
      - fonts.yml
      - alacritty.yml
  roles:
    - dotfiles
