---
all:
  hosts:
    dynamic:
      ansible_host: "{{ dynamic_host | default('localhost') }}"
      ansible_port: "{{ dynamic_port | default('22') }}"
      ansible_user: "{{ dynamic_user | default('root') }}"
