---

- name: Deploy mako
  hosts: all
  become: true
  vars_files:
    - ./vars/fonts.yml
    - ./vars/colorscheme.yml
  vars:
    dotfile_tasks:
      - fonts.yml
      - mako.yml
  roles:
    - dotfiles
